### ISSUE TITLE
[BUG] ci does not run because we have master as the default branch

### ISSUE THREAD

**Issue by line-o** [eXist-db/crypto-exist-java-lib#44]
The CI workflow configuration does not run because the default branch is `master` and not `main`

refs https://github.com/eXist-db/crypto-exist-java-lib/pull/39/files

Ways forward would be

1. switch to `main` as the default branch
2. change CI workflow to act on pushes and pull requests to `master`

**Comment by line-o** [comment]
I am all in for option 1 and if I understand @adamretter he is also in favour of this solution.

**Comment by windauer** [comment]
I don't care to be honest but if @adamretter and @line-o are all in for `main` I'm happy to go with main.

**Comment by adamretter** [comment]
@line-o I agree, we should look forward rather than back. Do you want me to do the honours? or do you prefer to do it?

**Comment by line-o** [comment]
@adamretter the stage is yours :)

**Comment by joewiz** [comment]
I've renamed the branch to `main`, and CI immediately kicked off: https://github.com/eXist-db/crypto-exist-java-lib/actions.
